#!/bin/bash
set -e
TMPDIR=${TMPDIR:-/tmp}

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

logs=/opt/resource/logs/check.log
touch $logs

payload=$TMPDIR/echo-request
cat > $payload <&0

ref=$(date '+%Y.%M.%d-%H:%M:%S')
versions='[{"ref": "'$ref'"}]'
echo $versions >> $logs
echo $versions >&3
