#!/bin/bash
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1
mkdir -p $destination
env > $destination/environment

echo '{ "version" : {}, "metadata": []  }' >&3
